feature/YH-142: Updating the layout
YeaHubTeam/yeahub-admin pull request #24
Opened 2024-06-12 23:43 UTC by Yuriykant

2024-06-13 09:41 UTC, PerelomaDenis requested changes

2024-06-13 09:41 UTC, PerelomaDenis commented on src/features/auth/ui/LoginForm/LoginForm.tsx
>  import React, { useState } from 'react';
компонент будет лежать в features/auth/login/ui

2024-06-13 09:41 UTC, PerelomaDenis commented on src/features/auth/ui/LogoutButton/LogoutButton.tsx
> +import React, { FC } from 'react';
должен лежать в features/auth/logout/ui

2024-06-13 09:41 UTC, PerelomaDenis commented on src/features/auth/ui/LogoutButton/LogoutButton.tsx
> +		if (!token) {
Проверка лишняя, так токен будет в любом случае

2024-06-13 09:41 UTC, PerelomaDenis commented on src/features/auth/ui/LogoutButton/LogoutButton.tsx
> +	const [logout] = useLogOutMutation();
Получи тут еще isLoading

2024-06-13 09:41 UTC, PerelomaDenis commented on src/features/auth/ui/LogoutButton/LogoutButton.tsx
> +		<button onClick={handleLogout} className={styles.button}>
Добавь disabled={isLoading}

2024-06-13 09:41 UTC, PerelomaDenis commented on src/features/auth/ui/LogoutButton/LogoutButton.tsx
> +		await logout({ token })
Такой вид надо будет поправить, но в следующей задаче

2024-06-13 09:41 UTC, PerelomaDenis commented on src/features/auth/ui/LoginForm/LoginForm.tsx
> +	const [login] = useLoginMutation();
получить isLoading и добавить на кнопку disabled

2024-06-13 09:41 UTC, PerelomaDenis commented on src/features/auth/ui/PrivateRoute/PrivateRoute.tsx
> +	useEffect(() => {
Вот это лучше делать не здесь. Давай перенесем в MainPage

2024-06-13 09:41 UTC, PerelomaDenis commented on src/pages/Users/ui/UsersPage.tsx
> +const UsersPage: FC = () => {
FC убираем

2024-06-13 09:41 UTC, PerelomaDenis commented on src/shared/assets/icons/LayoutToggleBtn.tsx
> +export const LayoutToggleBtn: FC<ImgCastom> = () => {
FC убираем, и интерфейс даже не используется

2024-06-13 09:41 UTC, PerelomaDenis commented on src/shared/ui/AppLogo/ui/AppLogo.tsx
> +export const AppLogo: FC<AppLogoProps> = ({ isOpen, setIsOpen }) => {
FC убираем, тип пропсов указываем у самих пропсов

2024-06-21 18:06 UTC, Yuriykant commented on src/features/auth/ui/PrivateRoute/PrivateRoute.tsx
> +	useEffect(() => {
расположение в features/auth логически соответствует защите маршрутов, требующих аутентификации, лучше следовать принципам FSD и держать PrivateRoute в features/auth

2024-06-21 22:05 UTC, PerelomaDenis requested changes

2024-06-21 22:05 UTC, PerelomaDenis commented on src/shared/ui/AppLogo/ui/AppLogo.tsx
> +	const handleToggleSidebar = () => {
Не вижу смысла прокидывать setisOpen и создавать тут функцию. Проще же сразу выше создать эту фунцию и прокинуть

2024-06-21 22:05 UTC, PerelomaDenis commented on src/features/auth/model/types/auth.ts
> +export interface LoginInput {
Некорректное место, перемести этот файл в entities/auth/types

2024-06-21 22:09 UTC, PerelomaDenis commented on src/features/auth/ui/LogoutButton/LogoutButton.tsx
> +		if (!token) {
Если нет токена, значит мы не может тут оказаться. Так как мы будет на странице авторизации. 
И получится, что при вызове запроса даже если токена не будет в хедерах, в идеале должен вызываться запрос на рефреш(но в админке его пока нет). Но все равно эта проверка лишняя

2024-06-22 08:40 UTC, PerelomaDenis submitted a review, later dismissed

2024-06-22 13:43 UTC, MirgradR submitted a review, later dismissed

2024-06-23 20:57 UTC, Yuriykant commented
Updating the layout

2024-06-25 13:37 UTC, PerelomaDenis approved these changes

2024-06-25 13:40 UTC, Serhio46 approved these changes

2024-06-25 13:41 UTC, merged